### ISSUE TITLE
sasl conversation error: unable to authenticate using mechanism "SCRAM-SHA-1"

### ISSUE THREAD

**Issue by ksponomarev** [litmuschaos/litmus#3781]
Hello

We are trying to connect our litmus with our mongodb with LDAP auth. After trying we have this error:
```
time="2022-10-04T14:20:43Z" level=info msg="Go Version: go1.16.15"
time="2022-10-04T14:20:43Z" level=info msg="Go OS/Arch: linux/amd64"
time="2022-10-04T14:20:45Z" level=fatal msg="failed to create collection connection() error occured during connection handshake: auth error: sasl conversation error: unable to authenticate using mechanism \"SCRAM-SHA-1\": (AuthenticationFailed) Authentication failed."
```

What should we do with it?

Thank you

**Comment by neelanjan00** [comment]
@AmitKumarDas, can you PTAL?

**Comment by neelanjan00** [comment]
@amityt can you PTAL?

**Comment by gdsoumya** [comment]
@ksponomarev in case you want to try it out here are the custom images for graphql-server and auth-server that you can replace in your setup to see if that fixes the problem.
- gdsoumya/litmusportal-server:mongofix
- gdsoumya/litmusportal-auth-server:mongofix

Both of them are using master code but I don't think there should be any problem if you are running a recent tagged version.

**Comment by ksponomarev** [comment]
@gdsoumya Now I have this error:
```time="2022-10-12T10:28:23Z" level=fatal msg="failed to create collection connection() error occured during connection handshake: auth error: unable to authenticate using mechanism \"PLAIN\": (AuthenticationFailed) Authentication failed."
```
Changed error from SCRAM-SHA-1 to PLAIN ))

**Comment by gdsoumya** [comment]
Have you set the db password and username in the secret properly?

**Comment by gdsoumya** [comment]
Also i just noticed you have mentioned a db name in the connection string, that won't work because litmus has a specific db that it uses, one db for auth-related stuff and another for the graphql. You would have to either manually create the specifc dbs yourself and use them separately in the 2 deployments or skip mentioning the dbname and let the servers create the db as needed.

**Comment by ksponomarev** [comment]
@gdsoumya 
Where can I change db names in helm chart?
I've changed DB_SERVER to:

**Comment by gdsoumya** [comment]
There is no way to change the db names it's fixed in code, what you should try rather is setting the URL to 
```
host-mdb01.example.com:27017,host-mdb02.example.com:27017,host-mdb03.example.com:27017/?authMechanism=PLAIN&readPreference=primary&authSource=%24external&replicaSet=rs0&tls=false
```
And let the servers create the dbs as needed (the credentials should have enough permission to create the databases or you can create the 2 dbs with the same name as I mentioned and allow the creds to have write access to the 2 databases)

**Comment by ksponomarev** [comment]
@gdsoumya 
Hello
I changed my connection string to this
```
mongodb://example-mdb01.example.ru:27017,example-mdb02.example.ru:27017,example-mdb03.example.ru:27017/?authMechanism=PLAIN&readPreference=primary&authSource=%24external&replicaSet=rs0&tls=false
```
And now have this error
```
time="2022-10-13T14:54:15Z" level=info msg="Go Version: go1.16.15"
time="2022-10-13T14:54:15Z" level=info msg="Go OS/Arch: linux/amd64"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0xbd54d0]

goroutine 1 [running]:
litmus/litmus-portal/authentication/pkg/utils.MongoConnection(0xc000100120, 0xc000030040, 0x0)
	/auth-server/pkg/utils/mongo_database.go:19 +0xd0
main.main()
	/auth-server/api/main.go:57 +0x10a
```

After that I changed string to 
```
mongodb://example%40example.ru:%23uWv%3F0z%3BLJs%7Dd%3FA~%3FxyQ3%5E@example-mdb01.example.ru:27017,example-mdb02.example.ru:27017,example-mdb03.example.ru:27017/?authMechanism=PLAIN&readPreference=primary&authSource=%24external&replicaSet=rs0&tls=false
```

I got this
```
time="2022-10-13T15:13:57Z" level=info msg="Go Version: go1.16.15"
time="2022-10-13T15:13:57Z" level=info msg="Go OS/Arch: linux/amd64"
time="2022-10-13T15:13:57Z" level=fatal msg="failed to create collection  connection() error occured during connection handshake: auth error: unable to authenticate using mechanism \"PLAIN\": (AuthenticationFailed) Authentication failed."
```

**Comment by Avyukth** [comment]
hey @ksponomarev  how did you solved it ?

**Comment by ksponomarev** [comment]
I guess I didn't. I don't remember. I haven't been using litmus since then
