### ISSUE TITLE
Fix code generation for Chaos Center Authentication API

### ISSUE THREAD

**Issue by smitthakkar96** [litmuschaos/litmus#4537]
While addressing [issue #4236](https://github.com/litmuschaos/litmus/issues/4236), I introduced a new endpoint to the Auth Server's capabilities. Following the steps in [this documentation](https://github.com/litmuschaos/litmus/blob/master/chaoscenter/authentication/DOC_SETUP.md), I regenerated the swagger.json.

During frontend development, I noticed the auth client is generated using [oats](https://github.com/harness/oats), but the [oats config](https://github.com/litmuschaos/litmus/blob/master/chaoscenter/web/config/oats.config.ts) points to a manually generated swagger.json at a different [location](https://raw.githubusercontent.com/litmuschaos/litmus/master/mkdocs/docs/auth/v3.0.0/auth-api.json), not the auto-generated one. Switching to the [auto-generated swagger.json](https://github.com/litmuschaos/litmus/blob/master/chaoscenter/authentication/api/docs/swagger.json) led to several issues:

### Missing Version

This can be corrected by setting `@Version` [here](https://github.com/litmuschaos/litmus/blob/master/chaoscenter/authentication/api/main.go#L53).

``` shell
⠋ Generating spec for: authTypeError: Cannot read properties of undefined (reading 'startsWith')
    at loadSpecFromFileOrUrl (file:///Users/s.thakkar/projects/litmus/chaoscenter/web/node_modules/@harnessio/oats-cli/dist/loadSpecFromFileOrUrl.mjs:58:42)
    at async importSpec (file:///Users/s.thakkar/projects/litmus/chaoscenter/web/node_modules/@harnessio/oats-cli/dist/importSpec.mjs:63:30)
✖ Generating spec for: auth
```

### Missing `operationId`

This can be corrected by adding `@ID` for every handler. Example

```golang
// FetchUsers		godoc
//
//	@Description	Fetch users.
//	@Tags			UserRouter
//	@Accept			json
//	@Produce		json
//	@Failure		401	{object}	response.ErrUnauthorized
//	@Failure		500	{object}	response.ErrServerError
//	@Success		200	{object}	response.UserResponse{}
//	@Router			/users [get]
//	@ID				users
```

```shell
⠋ Generating spec for: authError: Every path must have a operationId - No operationId set for post /auth/accept_invitation
    at file:///Users/s.thakkar/projects/litmus/chaoscenter/web/node_modules/@harnessio/oats-cli/dist/pathHelpers.mjs:38:23
    at Array.forEach (<anonymous>)
    at file:///Users/s.thakkar/projects/litmus/chaoscenter/web/node_modules/@harnessio/oats-cli/dist/pathHelpers.mjs:32:23
    at Array.forEach (<anonymous>)
    at processPaths (file:///Users/s.thakkar/projects/litmus/chaoscenter/web/node_modules/@harnessio/oats-cli/dist/pathHelpers.mjs:29:38)
    at Object.generate (file:///Users/s.thakkar/projects/litmus/chaoscenter/web/node_modules/@harnessio/oats-plugin-react-query/dist/generateReactQueryHooks.mjs:26:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async generateOpenAPISpec (file:///Users/s.thakkar/projects/litmus/chaoscenter/web/node_modules/@harnessio/oats-cli/dist/generateOpenAPISpec.mjs:27:32)
    at async importSpec (file:///Users/s.thakkar/projects/litmus/chaoscenter/web/node_modules/@harnessio/oats-cli/dist/importSpec.mjs:63:30)
✖ Generating spec for: auth
```

After resolving these, I observed a huge diff in the client code, likely due to some responses not being composed of struct types and missing annotations on some structs.

![Screenshot 2024-03-17 at 15 13 43](https://github.com/litmuschaos/litmus/assets/10204970/aa864117-bd4a-4605-92d0-a097f7d15a00)

## Proposed Solution

- [ ] Add missing version information
- [ ] Add `@ID` for all routes
- [ ] Annotate response structs

**Comment by rootxrishabh** [comment]
@smitthakkar96 I would like to work on this!

**Comment by smitthakkar96** [comment]
@rootxrishabh thanks for expressing interest. I am not tackling this currently so go ahead but I would suggest aligning with the maintainers first. You can also join the slack channel https://app.slack.com/client/T09NY5SBT/CNXNB0ZTN

cc: @Saranya-jena @neelanjan00 @namkyu1999

**Comment by rootxrishabh** [comment]
@smitthakkar96 I had joined the slack channel earlier. I will post my approach here before making a PR to get everyone's opinion. Sounds good?

**Comment by smitthakkar96** [comment]
Yup sounds good

**Comment by neelanjan00** [comment]
CC: @amityt can you please take a look?

**Comment by rootxrishabh** [comment]
Apologies folks, I currently don't have the bandwidth to complete this. Please feel free to take it up!

**Comment by bhoopesh369** [comment]
I would like to work on this 
@Saranya-jena @neelanjan00 @namkyu1999

**Comment by namkyu1999** [comment]
go ahead, @bhoopesh369

**Comment by bhoopesh369** [comment]
![IMG-20240610-WA0001.jpg](https://github.com/litmuschaos/litmus/assets/82646284/a092876a-f0fe-413e-bc5d-30bd59f92b1f)


So like I had to add this @param annotation for it to reference an object for the request # body (entities.MemberInput)

But swagger was not able to parse it and throwed an error saying : 
'cannot find type definition: entities.MemberInput'

So I looked into the swag docs, 
The object we need to reference here is from the entities module which is present in the authentication/pkg dir
It seems swag cannot parse files in outside dirs by default.

![IMG-20240610-WA0002.jpg](https://github.com/litmuschaos/litmus/assets/82646284/814b9601-7917-4a50-b428-a912fb6f01a5)

So I had to include the --parseDependency flag in the swag init command 

But this makes the 'swag init' go through unwanted files inside dependencies, thus taking more time than previously it took.

Should I use the flag and continue ?
OR 
Should I change the files/folder structure for it to be inside ?

**Comment by bhoopesh369** [comment]
I have mostly completed the work
Will give pr once done
